<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Logistics\DB\Tenant\Country;

class ZoneTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $panama = Country::where('name', 'Panamá')->first();

        $zones = [
            ['name' => 'Bocas del Toro', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bastimentos', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cauchero', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Punta Laurel', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tierra Oscura', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Changuinola', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Almirante', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cochigro', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Empalme', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guabito', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Gloria', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Delicias', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Tablas', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nance de Risco', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Teribe', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Valle del Risco', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Valle de Agua', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chiriquí Grande', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bajo Cedro', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Miramar', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Punta Peña', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Punta Robalo', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rambala', 'country_id' => $panama->id, 'department_id' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Alanje', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Divalá', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Canta Gallo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Tejar', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guarumal', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nuevo México', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Querévalo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palo Grande', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santo Tomás', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Armuelles', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Baco', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Limones', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Progreso', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rodolfo Aguilar Delgado', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Boquerón', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bágala', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cordillera', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guabal', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guayabal', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paraíso', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pedregal', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tijeras', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bajo Boquete', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Alto Boquete', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Caldera', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Jaramillo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Naranjos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palmira', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Concepción', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Aserrío de Gariché', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bugaba', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro Punta', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Bongo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gómez', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Estrella', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Andrés', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Marta', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Rosa', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santo Domingo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Solano', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sortová', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Volcán', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'David', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bijagual', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cochea', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chiriquí', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guacá', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Lomas', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pedregal', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Carlos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Pablo Nuevo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Pablo Viejo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Dolega', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Dos Ríos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Algarrobos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Anastacios', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Potrerillos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Potrerillos Abajo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rovira', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tinajas', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gualaca', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Hornito', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Angeles', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paja de Sombrero', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rincón', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Remedios', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Nancito', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Porvenir', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Puerto', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Lucía', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Remedios', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Nancito', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Porvenir', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Puerto', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Lucía', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Lajas', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lajas Adentro', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Juay', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Félix', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Cruz', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Horconcitos', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Boca Chica', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Boca del Monte', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Juan', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Lorenzo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tolé', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bella Vista', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro Viejo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cristo', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Justo Fidel Palacios', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lajas de Tolé', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Potrero de Caña', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Quebrada de Piedra', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Veladero', 'country_id' => $panama->id, 'department_id' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Aguadulce', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barrios Unidos', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cristo', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Roble', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pocrí', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Antón', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Caballero', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cabuya', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Chirú', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Retiro', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Valle', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Juan Díaz', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Hato', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Juan de Dios', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Rita', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Pintada', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Harino', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Potrero', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Lomas', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Grande', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Piedras Gordas', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Natá', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Capellanía', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Caño', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guzmán', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Huacas', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Toza', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Olá', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Copé', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Palmar', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Picacho', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Pava', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Penonomé', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cañaveral', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Coclé', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chiguirí Arriba', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Coco', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Valle de San Miguel', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pajonal', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Grande', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Indio', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Toabré', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tulú', 'country_id' => $panama->id, 'department_id' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barrio Norte', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barrio Sur', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Buena Vista', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cativá', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ciricito', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cristóbal', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Escobal', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Limón', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nueva Providencia', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Pilón', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sabanitas', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Salamanca', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Juan', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Rosa', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nuevo Chagres', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Achiote', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Guabo', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Encantada', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palmas Bellas', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Piña', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Salud', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Miguel de la Borda', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Coclé del Norte', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Guásimo', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gobea', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Indio', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José del General', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Portobelo', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cacique', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Garrote', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Isla Grande', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'María Chiquita', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palenque', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cuango', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Miramar', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nombre de Dios', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palmira', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Playa Chiquita', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Isabel', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Viento Frío', 'country_id' => $panama->id, 'department_id' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Palma', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Agua Fría', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Camoganti', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chepigana', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cucunatí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Garachiné', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Jaqué', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Piña', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Congo', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Iglesias', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sambú', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Setegantí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Taimatí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tucutí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Congo Arriba', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Fe', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Real de Santa María', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Boca de Cupe', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paya', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pinogana', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Púcuro', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Yape', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Yaviza', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Metetí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Wargandí', 'country_id' => $panama->id, 'department_id' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chitré', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Arena', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Monagrillo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Bonito', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Juan Bautista.', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Minas', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chepo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chumical', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Toro', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Leones', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Quebrada del Rosario', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Quebrada El Ciprián', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Pozos', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Capurí', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Calabacito', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cedro', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Arena', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Pitaloza', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Cerritos', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Cerros de Paja', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Llanas', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ocú', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro Largo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Tijera', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Entradero del Castillo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Llanos', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Grande', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Menchaca', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Peñas Chatas', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Parita', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cabuya', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Castillos', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano de la Cruz', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'París', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Portobelillo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Potuga', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pesé', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Cabras', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Pájaros', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Barrero', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Pedregoso', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Ciruelo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sabanagrande', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rincón Hondo', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa María', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chupampa', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Rincón', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Limón', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Canelos', 'country_id' => $panama->id, 'department_id' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guararé', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Espinal', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Macano', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guararé Arriba', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Enea', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Pasera', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Trancas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Abajo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Hato', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Perales', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Tablas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bajo Corral', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bayano', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Carate', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cocal', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Manantial', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Muñoz', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Pedregoso', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Laja', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Miel', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Palma', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Tiza', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Palmitas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Tablas Abajo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nuario', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Palmira', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Peña Blanca', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Hondo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Miguel', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santo Domingo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Sesteadero', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Valle Rico', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Vallerriquito', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Villa de Los Santos', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Ejido', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Guásimo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Colorada', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Espigadilla', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Cruces', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Guabas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Ángeles', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Olivos', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Largo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sabanagrande', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Agustín', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Ana', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tres Quebradas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Villa Lourdes', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Agua Buena', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Macaracas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bahía Honda', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bajos de Güera', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Corozal', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chupá', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cedro', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Espino Amarillo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Mesa', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano de Piedras', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Palmas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mogollón', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pedasí', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Asientos', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mariabé', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Purio', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Oria Arriba', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pocrí', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cañafístulo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lajamina', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paraíso', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Paritilla', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tonosí', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Altos de Güera', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cañas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Bebedero', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cacao', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cortezo', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Flores', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guánico', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Tronosa', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cambutal', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Isla de Cañas', 'country_id' => $panama->id, 'department_id' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Miguel', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Ensenada', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Esmeralda', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Guinea', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pedro González', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Saboga', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chepo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cañita', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chepillo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Llano', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Margaritas de Chepo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Cruz de Chinina', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tortí', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Madugandí', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chimán', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Brujas', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gonzalo Vásquez', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pásiga', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Unión Santeña', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ciudad de Panamá ', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '24 de Diciembre', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Alcalde Díaz', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ancón', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Betania', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bella Vista', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Calidonia', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Caimitillo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chilibre', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Chorrillo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Curundú', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ernesto Córdoba Campos', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Juan Díaz', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Cumbres', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Mañanitas', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pacora', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Parque Lefevre', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pedregal', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pueblo Nuevo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Abajo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Felipe', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Francisco', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Martín', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Ana', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tocumen', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Amelia Denis De Icaza', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Belisario Porras', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'José Domingo Espinar', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mateo Iturralde', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Victoriano Lorenzo', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Arnulfo Arias', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Belisario Frías', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Omar Torrijos', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rufina Alfaro', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Taboga', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Otoque Occidente', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Otoque Oriente', 'country_id' => $panama->id, 'department_id' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Arraiján', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Burunga', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro Silvestre', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Juan Demóstenes Arosemena', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nuevo Emperador', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Clara', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Veracruz', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Vista Alegre', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Capira', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Caimito', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Campana', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cermeño', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cirí de Los Sotos', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cirí Grande', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cacao', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Trinidad', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Ollas Arriba', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lídice', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Villa Carmen', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Villa Rosario', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Rosa', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chame', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bejuco', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Buenos Aires', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cabuya', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chicá', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Líbano', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Lajas', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Nueva Gorgona', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Punta Chame', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sajalices', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Sorá', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Chorrera', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barrio Balboa', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barrio Colón', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Amador', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Arosemena', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Arado', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Coco', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Feuillet', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guadalupe', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Herrera', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Hurtado', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Iturralde', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Represa', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Díaz', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mendoza', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Obaldía', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Playa Leona', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Caimito', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Rita', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Carlos', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Espino', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Higo', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guayabito', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Ermita', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Laguna', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Uvas', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Llanitos', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José', 'country_id' => $panama->id, 'department_id' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Atalaya', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Barrito', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Carrillo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Montañuela', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Antonio', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Calobre', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Barnizal', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Chitra', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cocla', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Potrero', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Laguna', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Raya de Calobre', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Tetilla', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Yeguada', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Guías', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Monjarás', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cañazas', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro de Plata', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Aromillo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Picador', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Cruces', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Valles', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Marcelo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Mesa', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bisvalles', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Boró', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Higo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Milagros', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Llano Grande', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Bartolo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Palmas', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cerro de Casa', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Corozal', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El María', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Prado', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Rincón', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Lolá', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Manuel Amador Guerrero', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pixvae', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Puerto Vidal', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Martín de Porres', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Viguí', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Zapotillo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Mariato', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Arenas', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cacao', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Quebro', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Tebario', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Montijo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cébaco', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Costa Hermosa', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gobernadora', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Garceana', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Leones', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Pilón', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Unión del Norte', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río de Jesús', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Catorce de Noviembre', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Las Huacas', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Castillos', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Utira', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Francisco', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Corral Falso', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Hatillos', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Remance', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Juan', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San José', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santa Fe', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Calovébora', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Alto', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Cuay', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Pantano', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Gatuncito', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Luis', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rubén Cantú', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Santiago', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Canto del Llano', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Carlos Santana Ávila', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Edwin Fábrega', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Llanito', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Colorada', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Peña', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Raya de Santa María', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Soledad', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Los Algarrobos', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Ponuga', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Martín de Porres', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'San Pedro del Espino', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rincón Largo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Urracá', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Soná', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Bahía Honda', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Calidonia', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Cativé', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'El Marañón', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Guarumal', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Hicaco', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'La Soledad', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Quebrada de Oro', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Río Grande', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => 'Rodeo Viejo', 'country_id' => $panama->id, 'department_id' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        \DB::table('zones')->insert($zones);
    }
}
